
services:
    postgres:
        image: postgres:15-alpine
        restart: unless-stopped
        environment:
            - PG_USER=${PG_USER:-user}
            - PG_PASSWORD=${PG_PASSWORD:-password}
            - PG_DB=${PG_DB:-is-assignment}
        volumes:
            - pgdata:/var/lib/postgresql/data
        ports:
            - "${PG_PORT:-5433}:5432"

    redis:
        image: redis:7-alpine
        restart: unless-stopped
        ports:
            - "${REDIS_PORT:-6380}:6379"

    kafka:
        image: bitnamilegacy/kafka:3.3.2
        restart: unless-stopped
        environment:
            - KAFKA_BROKER_ID=1
            - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092
            - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:${KAFKA_PORT},PLAINTEXT_INTERNAL://kafka:9092
            - KAFKA_ALLOW_PLAINTEXT_LISTENER=yes
            - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
        ports:
            - "${KAFKA_PORT}:9092"

volumes:
    pgdata:
